config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :tables

  # Defines the root path route ("/")
  root "tables#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game_state.rb
class GameState < ApplicationRecord
  def goal!
    self.score += 1
    save!
  end

  def reset!
    update!(score: 0)
  end

  def self.instance
    first_or_create(name: 'all-in')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery if: -> { false }
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :get_instance

  def index
    @state
  end

  def create
    @state.goal!
    ActionCable.server.broadcast('goal_channel', { body: 'Goaaaalll!!!', score: @state.score })
    render json: @state.score
  end

  def destroy
    @state.reset!
  end

  private

  def get_instance
    @state = GameState.instance
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Game</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Un-Minified version -->
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tables/index.html.erb
<h3>Web3 Game</h3>

<div data-controller="table"
     data-table-shot-url-value="<%= tables_path %>">
  <h1 id="score" data-table-target="output"><%= @state.score %></h1>
  <button data-action="click->table#shoot">Shoot</button>
</div>